Django/belt_reviewer/apps/books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^add$', views.add, name='add')
]

Django/belt_reviewer/apps/login/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
]

Django/belt_reviewer/belt_reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace='login')),
    url(r'^books/', include('apps.books.urls', namespace='books'))
]

Django/belt_reviewer/apps/books/models.py
from __future__ import unicode_literals
from django.db import models
from ..login.models import User, UserManager

class Author(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, related_name='books')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Review(models.Model):
    review = models.TextField()
    rating = models.IntegerField()
    book = models.ForeignKey(Book, related_name='book_reviews')
    user = models.ForeignKey(User, related_name='user_reviews')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/belt_reviewer/apps/login/models.py
from __future__ import unicode_literals
from django.db import models
import re, bcrypt

class UserManager(models.Manager):
    def validate(self, data, action):
        # obtain form values
        email = data['email']
        password = data['password']
        if action == 'register':
            first_name = data['first_name']
            last_name = data['last_name']
            confirm_password = data['confirm_password']

        # define regular expressions and error flag
        name_regex = re.compile(r'^[a-zA-Z]+$')
        email_regex = re.compile(
            r'^[a-zA-Z0-9.!#$%&\u2019*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)+$')
        valid = True
        password_regex = re.compile(r'^(?=.*[A-Z])(?=.*\d).{8,}$')
        messages = []

        # make sure there are no blank fields
        for i in data:
            if len(data[i]) == 0:
                messages.append('Error: All fields are required.')
                valid = False
                break

        # first and last name may only contain letters
        if action == 'register':
            if len(first_name) < 2 or len(last_name) < 2:
                messages.append(
                    'Error: First and last name must contain at least two characters.')
                valid = False
            elif not name_regex.match(first_name) or not name_regex.match(last_name):
                messages.append(
                    'Error: First and last name may not contain numbers or special characters.')
                valid = False

        # email format should be valid
        if len(email) > 0 and not email_regex.match(email):
            messages.append('Error: Invalid email format.')
            valid = False

        # password must be of at least medium strength
        if action == 'register':
            if not password_regex.match(password):
                message = 'Error: Password must be at least 8 characters in length '
                message += 'containing at least 1 uppercase letter, at least 1 number, and no spaces.'
                messages.append(message)
                valid = False

        # passwords should match
        if action == 'register':
            if password != confirm_password:
                messages.append('Error: Passwords do not match.')
                valid = False

        # check if email is registered
        count = User.objects.filter(email=email).count()
        if action == 'register' and count > 0:
            messages.append('Error: A user has already registered with that email.')
            valid = False
        
        # check if password matches
        if action == 'login':
            users = User.objects.filter(email=email)
            if len(users) == 0:
                messages.append('Error: No user has registered with that email.')
                valid = False
            elif not bcrypt.checkpw(password.encode(), str(users[0].password)):
                messages.append('Error: Password does not match.')
                valid = False

        # take action if valid, return error messages otherwise
        if valid:
            if action == 'register':
                hashed_pw = bcrypt.hashpw(
                    password.encode(),
                    bcrypt.gensalt()
                ).encode()
                user = User.objects.create(
                    first_name=first_name,
                    last_name=last_name,
                    email=email,
                    password=hashed_pw
                )
            elif action == 'login':
                user = User.objects.get(email=email)
            return (True, user)
        else:
            return (False, messages)

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.BinaryField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Django/belt_reviewer/apps/books/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse
from ..login.models import User, UserManager

def index(request):
    if 'id' not in request.session:
        redirect(reverse('login:index'))
    content = {
        'name': User.objects.get(id=request.session['id']).first_name
    }
    return render(request, 'books/index.html', content)

def logout(request):
    request.session.clear()
    return redirect(reverse('login:index'))

def add(request):
    return render(request, 'books/add.html')

Django/belt_reviewer/apps/login/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from .models import User, UserManager

def index(request):
    return render(request, 'login/index.html')

def register(request):
    um = UserManager()
    valid, response = um.validate(request.POST, 'register')
    if not valid:
        for message in response:
            messages.error(request, message)
        return redirect(reverse('login:index'))
    else:
        request.session['id'] = response.id

    return redirect(reverse('books:index'))

def login(request):
    um = UserManager()
    valid, response = um.validate(request.POST, 'login')
    if not valid:
        for message in response:
            messages.error(request, message)
        return redirect(reverse('login:index'))
    else:
        request.session['id'] = response.id

    return redirect(reverse('books:index'))

Django/belt_reviewer/apps/books/templates/books/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Book/Review</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'books/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
</head>
<body>
    <div class="container page">
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="nav-item" href="{% url 'quotes:index' %}">Home</a>
                </li>
                <li>
                    <a class="nav-item" href="{% url 'login:index' %}">Log Out</a>
                </li>
            </ul>
        </nav>
        <h4>Add a New Book Title and a Review:</h4>
    </div>
</body>
</html>

Django/belt_reviewer/apps/books/templates/books/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Books</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'books/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
</head>
<body>
    <div class="container page">
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <span class="navbar-brand">
                Welcome, {{ name }}!
            </span>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="nav-item" href="{% url 'books:add' %}">Add Book and Review</a>
                </li>
                <li>
                    <a class="nav-item" href="{% url 'login:index' %}">Log Out</a>
                </li>
            </ul>
        </nav>
        <div class="row">
            <div class="col-md-8">
                <h4>Recent Book Reviews:</h4>
            </div>
            <div class="col-md-4">
                <h4>Other Books with Reviews:</h4>
            </div>
        </div>
    </div>
</body>
</html>

Django/belt_reviewer/apps/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login and Registration</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
</head>
<body>
    <div class="container mt-15px">
        {% if messages %}
            {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
            {% endfor %}
        {% endif %}
        <div class="row">
            <div class="col-sm-6">
                <h3>Register</h3>
                <form action="{% url 'login:register' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="first_name" placeholder="First Name"
                        value="" class="form-control">
                    <input type="text" name="last_name" placeholder="Last Name"
                        value="" class="form-control">
                    <input type="text" name="email" placeholder="Email"
                        value="" class="form-control">
                    <input type="password" name="password" placeholder="Password"
                        class="form-control">
                    <input type="password" name="confirm_password" placeholder="Confirm Password"
                        class="form-control">
                    <input type="submit" value="Register" class="btn btn-primary mt-15px">
                </form>
            </div>
            <div class="col-sm-6">
                <h3>Log In</h3>
                <form action="{% url 'login:login' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" name="email" placeholder="Email" class="form-control">
                    <input type="password" name="password" placeholder="Password" class="form-control">
                    <input type="submit" value="Log In" class="btn btn-primary mt-15px">
                </form>
            </div>
        </div>
    </div>
</body>
</html>